# -*- coding: utf-8 -*-
"""portfolio_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZvnIO9GGI7QVfJK1YzG2aIR44JHv95R
"""

!pip install streamlit streamlit-extras pillow

import streamlit as st
from streamlit_extras.colored_header import colored_header
from PIL import Image

# ========== CONFIG ========== #
st.set_page_config(page_title="My Portfolio", page_icon=":rocket:", layout="wide")

# ========== CSS ========== #
st.markdown("""
    <style>
    body {
        background-color: #f6f8fa;
    }
    .main {
        background-color: #f6f8fa;
    }
    .section {
        background: white;
        border-radius: 2rem;
        box-shadow: 0 4px 32px rgba(0,0,0,0.10);
        padding: 2rem 2rem 1.5rem 2rem;
        margin-bottom: 2rem;
    }
    .icon-btn {
        background: #fff;
        border-radius: 100px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.10);
        padding: 0.6rem 0.7rem 0.5rem 0.7rem;
        margin-right: 1rem;
        border: none;
        display: inline-block;
        transition: 0.2s;
    }
    .icon-btn:hover {
        background: #e6eefa;
        transform: translateY(-3px) scale(1.07);
    }
    .logo-img {
        height:32px;
        vertical-align:middle;
    }
    .awards-badge {
        color: white;
        background: #7f56d9;
        border-radius: 10px;
        padding: 6px 18px;
        font-size: 1rem;
        margin-right: 10px;
        font-weight: 600;
    }
    .cert {
        background: #f0f9ff;
        padding: 10px 18px;
        border-radius: 10px;
        margin-bottom: 10px;
        font-weight: 500;
        border-left: 5px solid #7f56d9;
        box-shadow: 0 1px 8px rgba(127,86,217,0.08);
    }
    </style>
""", unsafe_allow_html=True)

# ========== MAIN LAYOUT ========== #
col1, col2 = st.columns([1, 2])

# -- Left Side Profile/Photo/Social Links --
with col1:
    st.image("https://avatars.githubusercontent.com/u/9919?s=280&v=4", width=160)  # Change to your photo/logo
    st.markdown("<h2 style='margin-top:0.5em;'>Manish Kumar</h2>", unsafe_allow_html=True)
    st.markdown("**Data Scientist | Azure Databricks | ML Engineer**")
    st.write("")
    # Download Resume Button
    with open("resume.pdf", "rb") as pdf_file:
        PDFbyte = pdf_file.read()
        st.download_button(label="⬇️ Download Resume", data=PDFbyte, file_name="Manish_Resume.pdf", mime='application/pdf')
    st.write("")
    # Social Buttons
    st.markdown(
        """
        <div>
            <a href="https://github.com/" target="_blank" class="icon-btn"><img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/github.svg" class="logo-img" title="GitHub"/></a>
            <a href="https://public.tableau.com/app/profile/" target="_blank" class="icon-btn"><img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/tableau.svg" class="logo-img" title="Tableau"/></a>
            <a href="https://www.linkedin.com/in/" target="_blank" class="icon-btn"><img src="https://cdn.jsdelivr.net/gh/simple-icons/simple-icons/icons/linkedin.svg" class="logo-img" title="LinkedIn"/></a>
        </div>
        """, unsafe_allow_html=True
    )

# -- Right Side Content --
with col2:
    # About Me
    st.markdown('<div class="section">', unsafe_allow_html=True)
    colored_header(label="About Me", description="", color_name="violet-70")
    st.write(
        """
        Hi, I'm Manish Kumar! 👋
        Experienced Data Scientist with a passion for building end-to-end AI solutions.
        Skilled in Python, Azure Databricks, ML/DL, and Data Engineering.
        I love solving real business problems with ML, analytics, and cloud technology.
        """
    )
    st.markdown('</div>', unsafe_allow_html=True)

    # Awards
    st.markdown('<div class="section">', unsafe_allow_html=True)
    colored_header(label="Awards", description="", color_name="violet-50")
    st.markdown("""
        <span class="awards-badge">🏅 Databricks Champion Award 2024</span>
        <span class="awards-badge">🏆 Azure Data Scientist of the Year</span>
        <span class="awards-badge">🥇 Power BI Dashboard Star</span>
    """, unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    # Certifications
    st.markdown('<div class="section">', unsafe_allow_html=True)
    colored_header(label="Certifications", description="", color_name="violet-30")
    st.markdown("""
        <div class="cert">Microsoft Certified: Azure Data Scientist Associate</div>
        <div class="cert">Databricks Certified Data Engineer Associate</div>
        <div class="cert">AWS Certified Solutions Architect – Associate</div>
        <div class="cert">Tableau Desktop Specialist</div>
    """, unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

st.markdown("<br><br>", unsafe_allow_html=True)
st.markdown("<center><small style='color:#A0AEC0;'>Made with ❤️ using Streamlit</small></center>", unsafe_allow_html=True)
